import "./globals.css";
import LenisProvider from "@/app/components/utils/LenisProvider";
import Footer from "@/app/components/footer/Footer";
import Header from "@/app/components/header/Header";

export const metadata = {
  title: "Simon Tessard - Création de sites web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LenisProvider>
          <Header/>
          {children}
          <Footer/>
        </LenisProvider>
      </body>
    </html>
  );
}
